name: Build iOS Project
on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install and Build
        run: |
          # This command finds where your package.json is and moves there
          cd $(find . -name package.json -exec dirname {} \;)
          npm install
          npm install @capacitor/core @capacitor/cli @capacitor/ios
          npm run build
          npx cap init "Wumpus Squad" com.wumpus.squad --web-dir dist
          npx cap add ios
          npx cap sync ios

      - name: Upload iOS Folder
        uses: actions/upload-artifact@v4
        with:
          name: ios-project-files
          path: "**/ios/App/"
